services:
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --save "" --appendonly no
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    restart: always

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
      - "127.0.0.1:8088:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8088/
      - SEARXNG_SECRET=${SEARXNG_SECRET}
    depends_on:
      - redis
    restart: always

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    network_mode: "host"

networks:
  searxng:
    ipam:
      driver: default

volumes:
  caddy_data:
  caddy_config:
