# SearXNG settings
general:
  debug: false
  instance_name: "SearchInlet SearXNG"

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "extremely-secret-key-for-search-inlet-production"

search:
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
  - name: duckduckgo
    engine: duckduckgo
